# Generated by Django 4.2.13 on 2024-07-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("your_name", models.TextField()),
                ("your_email", models.TextField()),
                ("role", models.IntegerField(null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="deadlines/"),
                ),
                ("group", models.TextField()),
                ("assigned_emails", models.TextField()),
            ],
        ),
    ]
